import { SupportedLocale } from '../locales/legal';

export type LegalSection = {
  heading: string;
  body: string[];
};

export type LegalDocument = {
  title: string;
  version: string;
  updatedAt: string;
  sections: LegalSection[];
  tables?: Array<{ heading: string; rows: Array<{ name: string; provider: string; purpose: string; category: string; duration: string; type: string }> }>;
};

type LegalDocs = Record<SupportedLocale, LegalDocument>;

const placeholders = {
  controller: '[COMPANY_NAME] – [REGISTERED_ADDRESS]',
  contactEmail: '[CONTACT_EMAIL]',
  vat: '[VAT_NUMBER]',
};

export const PRIVACY_POLICY: LegalDocs = {
  en: {
    title: 'Privacy Policy',
    version: '1.0.0',
    updatedAt: '2025-02-01',
    sections: [
      {
        heading: '1. Data controller and contact details',
        body: [
          `The service Reffo Review is provided by ${placeholders.controller}. For any privacy-related request you can write to ${placeholders.contactEmail}. If a Data Protection Officer is appointed, the contact will be published on this page.`,
        ],
      },
      {
        heading: '2. Categories of personal data processed',
        body: [
          'Account data: name, surname, company details, email address, authentication identifiers (managed by our identity provider).',
          'Usage data: IP address, device/ browser information, timestamps, activity logs strictly necessary to provide the service and keep it secure.',
          'Content data: videos, images, comments, annotations and files uploaded or generated by users inside Reffo Review.',
          'Cookies and tracking technologies: see the Cookie Policy for details about categories and third parties.',
        ],
      },
      {
        heading: '3. Purposes and legal bases',
        body: [
          'Contract performance: creating and managing accounts, providing collaboration features, processing payments, offering customer support.',
          'Legitimate interest: securing the platform, preventing abuse, analysing aggregated usage to improve stability, contacting users about critical changes.',
          'Consent: sending newsletters or marketing communications, enabling optional integrations, storing preferences through non-essential cookies.',
        ],
      },
      {
        heading: '4. Recipients and data transfers',
        body: [
          'Hosting providers and infrastructure vendors located in the EU/EEA or in countries offering adequate protection under Art. 45 GDPR, or covered by appropriate safeguards (e.g. Standard Contractual Clauses).',
          'Communication and productivity tools (email, support, analytics) strictly necessary for the operation of Reffo Review.',
          'Other collaborators explicitly authorised by the customer through the sharing features.',
          'A detailed list of processors is available upon request to the controller.',
        ],
      },
      {
        heading: '5. Data retention',
        body: [
          'Account data is retained for the lifespan of the contract plus the limitation period defined by applicable law.',
          'Content uploaded by users is retained until deleted by the owner or for as long as the workspace exists.',
          'Logs and security events are normally retained for up to 12 months unless required for investigations.',
          'Cookie identifiers are stored according to the durations declared in the Cookie Policy.',
        ],
      },
      {
        heading: '6. User rights',
        body: [
          'Data subjects may exercise their rights of access, rectification, erasure, restriction, portability, objection, and withdrawal of consent at any time by contacting the controller.',
          'Users in the EU can lodge a complaint with the competent Supervisory Authority (in Italy: Garante per la Protezione dei Dati Personali).',
        ],
      },
      {
        heading: '7. Security measures',
        body: [
          'We adopt administrative, technical, and physical safeguards appropriate to the risk: encryption in transit, access controls, audit logging, and regular vulnerability assessments.',
          'Despite these measures, no system can be guaranteed as 100% secure; users are encouraged to choose strong credentials and report suspicious behaviour.',
        ],
      },
      {
        heading: '8. Changes to this policy',
        body: [
          'Any material amendment will be communicated in advance through the platform or via email. Users will need to accept the updated version when required.',
        ],
      },
      {
        heading: '9. Exercising your rights',
        body: [
          `Requests can be sent to ${placeholders.contactEmail}. To protect your data we may ask for additional information to verify your identity before completing the request.`,
        ],
      },
    ],
  },
  it: {
    title: 'Informativa Privacy',
    version: '1.0.0',
    updatedAt: '01/02/2025',
    sections: [
      {
        heading: '1. Titolare del trattamento e contatti',
        body: [
          `Il servizio Reffo Review è gestito da ${placeholders.controller}. Per ogni richiesta in materia di protezione dati è possibile scrivere a ${placeholders.contactEmail}. Eventuali riferimenti al DPO saranno pubblicati in questa pagina.`,
        ],
      },
      {
        heading: '2. Tipologie di dati trattati',
        body: [
          'Dati account: nome, cognome, dati societari, email, identificativi di autenticazione (gestiti dal nostro identity provider).',
          'Dati di utilizzo: indirizzo IP, informazioni su dispositivo e browser, orari di accesso, log tecnici necessari per fornire il servizio e mantenerlo sicuro.',
          'Contenuti caricati: video, immagini, commenti, annotazioni e file generati dagli utenti all’interno di Reffo Review.',
          'Cookie e tecnologie simili: dettagli disponibili nella Cookie Policy.',
        ],
      },
      {
        heading: '3. Finalità e basi giuridiche',
        body: [
          'Esecuzione del contratto: creazione e gestione degli account, fornitura delle funzionalità collaborative, supporto clienti.',
          'Legittimo interesse: sicurezza della piattaforma, prevenzione abusi, analisi statistica aggregata per migliorarne la stabilità, comunicazioni relative a modifiche critiche.',
          'Consenso: invio di newsletter o comunicazioni commerciali, abilitazione di integrazioni opzionali, memorizzazione di preferenze tramite cookie non essenziali.',
        ],
      },
      {
        heading: '4. Destinatari e trasferimenti',
        body: [
          'Fornitori hosting e infrastruttura situati in UE/SEE o in Paesi ritenuti adeguati, oppure coperti da garanzie adeguate (es. Clausole Contrattuali Standard).',
          'Strumenti di comunicazione e produttività strettamente necessari per l’erogazione di Reffo Review.',
          'Collaboratori e contatti invitati dall’utente attraverso le funzionalità di condivisione.',
          'L’elenco completo dei responsabili del trattamento è disponibile su richiesta scrivendo al Titolare.',
        ],
      },
      {
        heading: '5. Conservazione dei dati',
        body: [
          'I dati account vengono conservati per tutta la durata del contratto e per il successivo periodo di prescrizione legale.',
          'I contenuti caricati dagli utenti restano disponibili finché non vengono eliminati dall’intestatario o per tutta la durata del workspace.',
          'I log tecnici e gli eventi di sicurezza vengono conservati fino a 12 mesi, salvo esigenze investigative.',
          'La durata dei cookie è indicata nella Cookie Policy.',
        ],
      },
      {
        heading: '6. Diritti degli interessati',
        body: [
          'Gli interessati possono esercitare i diritti previsti dagli artt. 15-22 GDPR (accesso, rettifica, cancellazione, limitazione, portabilità, opposizione, revoca del consenso) contattando il Titolare.',
          'In Italia è possibile proporre reclamo al Garante per la Protezione dei Dati Personali.',
        ],
      },
      {
        heading: '7. Misure di sicurezza',
        body: [
          'Adottiamo misure tecniche e organizzative adeguate al rischio: cifratura in transito, controlli di accesso, logging, periodiche verifiche di sicurezza.',
          'Nessun sistema può però garantire sicurezza assoluta: invitiamo gli utenti a utilizzare credenziali robuste e a segnalarci attività sospette.',
        ],
      },
      {
        heading: '8. Aggiornamenti dell’informativa',
        body: [
          'Eventuali modifiche sostanziali saranno comunicate in anticipo tramite la piattaforma o email. In caso di cambiamenti materiali potrà essere richiesto un nuovo consenso.',
        ],
      },
      {
        heading: '9. Esercizio dei diritti',
        body: [
          `Per esercitare i diritti è possibile scrivere a ${placeholders.contactEmail}. Per tutelare la sicurezza dei dati potremmo richiedere informazioni aggiuntive per verificare l’identità del richiedente.`,
        ],
      },
    ],
  },
};

export const COOKIE_POLICY: LegalDocs = {
  en: {
    title: 'Cookie Policy',
    version: '1.0.0',
    updatedAt: '2025-02-01',
    sections: [
      {
        heading: 'What are cookies?',
        body: [
          'Cookies are small text files stored on your device when you browse a website. They allow basic navigation, remembering preferences, and, with your consent, measuring audience or delivering personalized content.',
          'This policy applies to cookies, local storage, pixels, and similar technologies used within Reffo Review.',
        ],
      },
      {
        heading: 'Cookie categories',
        body: [
          'Strictly necessary: essential for login, security, and basic features. They are always active and do not require consent.',
          'Preferences: remember language, theme, or the last project opened. They are optional.',
          'Analytics: collect aggregated usage statistics to improve the service. If anonymization is insufficient, consent is required.',
        ],
      },
      {
        heading: 'Managing consent',
        body: [
          'You can manage consent at any time using the “Cookie settings” link in the footer or via the banner displayed at the first visit.',
          'Browser settings allow you to delete or block cookies. However, blocking strictly necessary cookies may impair the service.',
        ],
      },
    ],
    tables: [
      {
        heading: 'Cookie inventory (example placeholders)',
        rows: [
          { name: 'reffo_session', provider: 'Reffo Review', purpose: 'Keeps you authenticated and preserves workspace context.', category: 'Strictly necessary', duration: 'Session', type: 'First-party' },
          { name: 'reffo_consent', provider: 'Reffo Review', purpose: 'Stores the cookie preferences expressed by the user (proof of consent).', category: 'Strictly necessary', duration: '6 months', type: 'First-party' },
          { name: 'analytics_id', provider: '[ANALYTICS_VENDOR]', purpose: 'Aggregated traffic measurement (enable only if consented).', category: 'Analytics', duration: '[DURATION]', type: 'Third-party' },
        ],
      },
    ],
  },
  it: {
    title: 'Cookie Policy',
    version: '1.0.0',
    updatedAt: '01/02/2025',
    sections: [
      {
        heading: 'Cosa sono i cookie',
        body: [
          'I cookie sono piccoli file di testo salvati sul dispositivo durante la navigazione. Consentono funzionalità di base, memorizzano preferenze e, previo consenso, misurano il traffico o mostrano contenuti personalizzati.',
          'La presente informativa riguarda cookie, local storage, pixel e tecnologie analoghe utilizzate in Reffo Review.',
        ],
      },
      {
        heading: 'Categorie di cookie',
        body: [
          'Strettamente necessari: indispensabili per login, sicurezza e funzionalità di base. Sono sempre attivi.',
          'Preferenze: ricordano lingua, tema e layout preferiti. Richiedono il tuo consenso.',
          'Statistiche / Analytics: raccolgono dati aggregati sull’utilizzo per migliorare il servizio.',
        ],
      },
      {
        heading: 'Gestione del consenso',
        body: [
          'Puoi modificare le tue scelte in qualsiasi momento tramite il link “Impostazioni cookie” presente nel footer o dal banner che compare al primo accesso.',
          'Inoltre, i browser permettono di eliminare o bloccare i cookie: la disattivazione dei cookie strettamente necessari potrebbe compromettere alcuni servizi.',
        ],
      },
    ],
    tables: [
      {
        heading: 'Elenco dei cookie (esempi da completare)',
        rows: [
          { name: 'reffo_session', provider: 'Reffo Review', purpose: 'Mantiene la sessione attiva e protegge l’accesso.', category: 'Strettamente necessario', duration: 'Sessione', type: 'Prima parte' },
          { name: 'reffo_consent', provider: 'Reffo Review', purpose: 'Memorizza le preferenze espresse sul banner cookie.', category: 'Strettamente necessario', duration: '6 mesi', type: 'Prima parte' },
          { name: 'analytics_id', provider: '[FORNITORE_ANALYTICS]', purpose: 'Misura aggregata del traffico (attivo solo con consenso).', category: 'Statistiche', duration: '[DURATA]', type: 'Terza parte' },
        ],
      },
    ],
  },
};

export const TERMS_OF_USE: LegalDocs = {
  en: {
    title: 'Terms of Use',
    version: '1.0.0',
    updatedAt: '2025-02-01',
    sections: [
      { heading: '1. Scope', body: ['These Terms govern access to Reffo Review, a SaaS platform for uploading videos, collecting feedback, and collaborating with teammates and external reviewers. By creating an account or accessing shared content you agree to these Terms.'] },
      { heading: '2. Account registration', body: ['Users must provide accurate information and keep credentials secure. You are responsible for all activities carried out under your account. If you suspect unauthorised access, notify us immediately at ' + placeholders.contactEmail + '.'] },
      { heading: '3. Acceptable use', body: ['Do not upload illegal content, malware, or material infringing intellectual property rights.', 'Do not attempt to access other users’ workspaces unless invited, nor bypass security controls.', 'You remain solely responsible for the files and comments you upload.'] },
      { heading: '4. Intellectual property', body: ['Users retain ownership of the content they upload. By submitting content you grant Reffo Review a limited, worldwide, non-exclusive licence to host, process, transcode, and display that content solely to deliver the service.', 'All trademarks, logos, and software components of Reffo Review remain the exclusive property of [COMPANY_NAME].'] },
      { heading: '5. Third-party services', body: ['Certain features embed third-party services (e.g. storage, communication, analytics). Their use may be subject to separate terms, and you authorise us to share the minimum necessary data to enable them.'] },
      { heading: '6. Payment and plan changes', body: ['Paid plans are billed according to the pricing page. We may suspend the service for overdue invoices after providing notice.', 'We may update pricing or features by giving reasonable prior notice; continued use after the effective date constitutes acceptance.'] },
      { heading: '7. Suspension and termination', body: ['We may suspend or terminate access if you breach these Terms, engage in fraudulent/abusive behaviour, or if required by law.', 'You may cancel at any time; we will retain or delete data according to our Privacy Policy and contractual obligations.'] },
      { heading: '8. Liability', body: ['To the maximum extent permitted by law, the service is provided “as is”. We are not liable for indirect or consequential damages, loss of data, or loss of profits. Nothing limits liability for wilful misconduct or gross negligence.', 'In any case, our aggregate liability shall not exceed the fees paid by the customer in the previous 12 months.'] },
      { heading: '9. Governing law and jurisdiction', body: ['These Terms are governed by Italian law. Any dispute shall be submitted to the exclusive jurisdiction of the courts of [CITY], without prejudice to consumer protections where applicable.'] },
      { heading: '10. Changes to the Terms', body: ['We may update these Terms when introducing new features or due to regulatory changes. We will notify users in advance and request acceptance where legally required.'] },
    ],
  },
  it: {
    title: "Termini d'uso",
    version: '1.0.0',
    updatedAt: '01/02/2025',
    sections: [
      { heading: '1. Oggetto', body: ['I presenti Termini regolano l’accesso e l’utilizzo di Reffo Review, piattaforma SaaS per il caricamento di video, la raccolta di feedback e la collaborazione tra team e revisori esterni. L’uso del servizio implica l’accettazione integrale dei Termini.'] },
      { heading: '2. Creazione dell’account', body: ['L’utente deve fornire dati veritieri e custodire con diligenza le credenziali. Qualsiasi attività svolta tramite l’account è imputabile all’utente stesso. In caso di accesso non autorizzato scrivere a ' + placeholders.contactEmail + '.'] },
      { heading: '3. Uso consentito', body: ['È vietato caricare contenuti illegali, malware o materiali che violino diritti di proprietà intellettuale.', 'È vietato tentare di accedere a workspace altrui senza invito o aggirare le misure di sicurezza.', 'L’utente resta l’unico responsabile dei file e dei commenti caricati.'] },
      { heading: '4. Proprietà intellettuale', body: ['L’utente mantiene la titolarità dei contenuti caricati ma concede a Reffo Review una licenza limitata, mondiale e non esclusiva per ospitare, elaborare, transcodificare e mostrare tali contenuti al solo fine di erogare il servizio.', 'Marchi, loghi e software della piattaforma restano di esclusiva proprietà di [COMPANY_NAME].'] },
      { heading: '5. Servizi di terze parti', body: ['Alcune funzioni integrano servizi di terzi (storage, comunicazione, analytics). Il loro utilizzo può essere soggetto a termini separati e autorizzi la condivisione dei dati strettamente necessari.'] },
      { heading: '6. Pagamenti e variazioni del piano', body: ['I piani a pagamento sono fatturati secondo il listino pubblicato. In caso di mancato pagamento potremmo sospendere l’accesso previa comunicazione.', 'Eventuali modifiche economiche o funzionali saranno comunicate con congruo preavviso; l’uso continuato implica accettazione.'] },
      { heading: '7. Sospensione e cessazione', body: ['Possiamo sospendere o chiudere gli account che violano i Termini, agiscono in modo fraudolento/abusivo o quando lo richieda la legge.', 'L’utente può recedere in qualsiasi momento; conserveremo o elimineremo i dati secondo l’Informativa Privacy e gli obblighi contrattuali.'] },
      { heading: '8. Responsabilità', body: ['Nella misura massima consentita dalla legge il servizio è fornito “così com’è”. Non rispondiamo di danni indiretti, perdita di dati o di profitto. Resta ferma la responsabilità per dolo o colpa grave.', 'In ogni caso la nostra responsabilità complessiva non potrà superare i corrispettivi pagati nei 12 mesi precedenti.'] },
      { heading: '9. Legge applicabile e foro competente', body: ['I Termini sono regolati dalla legge italiana. Ogni controversia sarà devoluta alla competenza esclusiva del Foro di [CITTÀ], salva diversa disciplina inderogabile prevista per i consumatori.'] },
      { heading: '10. Modifiche', body: ['Eventuali modifiche saranno comunicate in anticipo tramite il portale o email. Qualora richiesto dalla normativa, sarà necessario prestare nuovamente il consenso.'] },
    ],
  },
};
