import { Annotation, Comment, AnnotationTool, Video, Project } from '../types';

export const mockProjects: Project[] = [
  { id: 'proj-1', name: 'Project Alpha', createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString() },
  { id: 'proj-2', name: 'Character Animations', createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString() },
  { id: 'proj-3', name: 'VFX Shots', createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString() },
];

export const mockVideos: Video[] = [
    {
    id: '1',
    title: 'Big Buck Bunny',
    src: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    width: 1280,
    height: 720,
    fps: 24,
    duration: 596,
    projectId: 'proj-1',
    uploadedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    lastReviewedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: '2',
    title: 'Elephants Dream',
    src: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    width: 1280,
    height: 720,
    fps: 24,
    duration: 653,
    projectId: 'proj-1',
    uploadedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
    lastReviewedAt: new Date(Date.now() - 1000 * 60 * 60 * 25).toISOString(),
  },
  {
    id: '3',
    title: 'For Bigger Blazes',
    src: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    width: 1280,
    height: 720,
    fps: 24,
    duration: 15,
    projectId: 'proj-2',
    uploadedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    lastReviewedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: '4',
    title: 'For Bigger Escapes',
    src: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    width: 1280,
    height: 720,
    fps: 24,
    duration: 15,
    projectId: 'proj-2',
    uploadedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
    lastReviewedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
  {
    id: '5',
    title: 'For Bigger Fun',
    src: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    width: 1280,
    height: 720,
    fps: 24,
    duration: 60,
    projectId: undefined,
    uploadedAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    lastReviewedAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: '6',
    title: 'Sintel',
    src: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    width: 1280,
    height: 720,
    fps: 24,
    duration: 888,
    projectId: 'proj-3',
    uploadedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
  },
];


export const annotations: Annotation[] = [
  {
    id: 'anno-1',
    videoId: '1',
    authorId: 'user-1',
    frame: 240,
    type: AnnotationTool.RECTANGLE,
    color: '#ef4444', // red-500
    lineWidth: 4,
    center: { x: 0.35, y: 0.425 },
    width: 0.2,
    height: 0.25,
    rotation: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'anno-2',
    videoId: '1',
    authorId: 'user-2',
    frame: 480,
    type: AnnotationTool.ARROW,
    color: '#38bdf8', // sky-400
    lineWidth: 5,
    start: { x: 0.8, y: 0.2 },
    end: { x: 0.6, y: 0.4 },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'anno-3',
    videoId: '1',
    authorId: 'user-1',
    frame: 480,
    type: AnnotationTool.FREEHAND,
    color: '#facc15', // yellow-400
    lineWidth: 3,
    points: [
      { x: 0.58, y: 0.42 },
      { x: 0.59, y: 0.41 },
      { x: 0.60, y: 0.43 },
      { x: 0.61, y: 0.42 },
      { x: 0.62, y: 0.44 },
    ],
    createdAt: new Date().toISOString(),
  },
];

export const comments: Comment[] = [
  {
    id: 'comm-1',
    videoId: '1',
    authorId: 'user-1',
    authorName: 'Alex',
    authorAvatar: 'https://i.pravatar.cc/150?u=alex',
    text: 'Can we make this explosion bigger?',
    frame: 240,
    resolved: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    position: { x: 0.4, y: 0.5 },
  },
  {
    id: 'comm-2',
    parentId: 'comm-1',
    videoId: '1',
    authorId: 'user-2',
    authorName: 'Brenda',
    authorAvatar: 'https://i.pravatar.cc/150?u=brenda',
    text: 'Yes, I think so. How much bigger?',
    resolved: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
  },
    {
    id: 'comm-3',
    videoId: '1',
    authorId: 'user-2',
    authorName: 'Brenda',
    authorAvatar: 'https://i.pravatar.cc/150?u=brenda',
    text: "The lighting on the character's face feels a bit flat here.",
    frame: 480,
    resolved: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    position: { x: 0.65, y: 0.35 },
  },
    {
    id: 'comm-4',
    videoId: '1',
    authorId: 'user-1',
    authorName: 'Alex',
    authorAvatar: 'https://i.pravatar.cc/150?u=alex',
    text: "Good point. Let's add a key light from the left.",
    resolved: true,
    frame: 480,
    createdAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
  },
];
